[workspace]
resolver = "2"
members = [
    "dhcp",
    "dns",
    "fuzz",
    "hl",
    "ll",
    "mqtt",
    "regsim",
    "sntp",
    "testsuite",
]
default-members = [
    "dhcp",
    "dns",
    "fuzz",
    "hl",
    "ll",
    "mqtt",
    "regsim",
    "sntp",
    "testsuite",
]
