[alias]
test-all = "test --features std,log,embedded-hal,time,chrono,num-rational,w5500-tls"
test-dhcp = "test -p w5500-dhcp --features log,std"
test-mqtt = "test -p w5500-mqtt --features log,std,w5500-tls"
test-regsim = "test -p w5500-regsim"
